### ISSUE TITLE
Бургер меню

### ISSUE THREAD

**Issue by ehotez** [ehotez/DashboardWeb#5]
![image](https://user-images.githubusercontent.com/85438019/230205461-4df8d2bd-d5e3-4a8c-a54a-98438edfe930.png)

**Comment by KorolLich** [comment]
БАГ при выборе размера сетки виджетов:
При нажатии кнопок "Выбор размера сетки", далее кнопка "Назад" в браузере, сайдбар выбора размеров сетки виджетов остается, хотя должен быть обычный
