### ISSUE TITLE
Идентификация пользователя

### ISSUE THREAD

**Issue by ehotez** [ehotez/DashboardWeb#9]
Определение пользователя и отображение только его источников
![image](https://user-images.githubusercontent.com/85438019/230335705-1040fb65-4081-4b7c-9d30-f79b0e32cff5.png)

**Comment by KorolLich** [comment]
БАГ: при выходе из системы можно напрямую все равно попасть на страницу localhost:3000/main, localhost:3000/sources, и т.д.
